version: "3.8"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www
        depends_on:
            - nginx
            - db

    nginx:
        image: nginx:alpine
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

    db:
        image: mysql:5.7
        platform: linux/amd64
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - dbdata:/var/lib/mysql

volumes:
    dbdata:
